spring:
  cloud:
    config:
      uri: http://localhost:8888                              # ${CONFIG_URI}
  config:
    import: "configserver:"
  application:
    name: user-micro-service-application
