server:
  port: 80
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: user-profile-service
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: userProfileCircuitBreaker
                fallbackUri: forward:/fallback/user
      default-filters:
        # http://localhost/auth/findbyid/1   --> demek aşağıdaki rewritepath
        # (?<segment>.*)      -->  auth/findbyid/1
        #  /$\{segment}       -->  http://localhost/auth/findbyid/1
        - RewritePath=/(?<segment>.*),  /$\{segment}