server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Java12Auth
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

#  Önemli
# şifre gibi baskalarının istemeyeceğimiz verileri yml dosyasında dahi tutmak sakıncalıdır.
# bu nedenle bizim bu bilgileri gizlememiz gereklidir.
# bu bilgileri gizlemek için Environment variable (Ortam değişkenleri tutabiliriz)


authserviceconfig:
  secrets:
    secret-key: ${JAVA12_SECRETKEY}
    issuer: ${JAVA12_ISSUER}