server:
  port: 9091

spring:
  security:
    user:
      name: java12
      password: 1234
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-server
  data:
    mongodb:
      host: localhost
      port: 29000
      database: UserProfileDB
      username: adminmongo
      password: root

#  jpa:
#    hibernate:
#      ddl-auto: update

#  Önemli
# şifre gibi baskalarının istemeyeceğimiz verileri yml dosyasında dahi tutmak sakıncalıdır.
# bu nedenle bizim bu bilgileri gizlememiz gereklidir.
# bu bilgileri gizlemek için Environment variable (Ortam değişkenleri tutabiliriz)


authserviceconfig:
  secrets:
    secret-key: ${JAVA12_SECRETKEY}
    issuer: ${JAVA12_ISSUER}

redisconfig:
  host: localhost
  port: 6379
